// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SEP24_Project

#ifndef _SEP24_PROJECT_UI_H
#define _SEP24_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1s2;
extern lv_obj_t * ui_PanelTok;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_PanelU;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_PanelW;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image5;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_cross_png);    // assets/Cross.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/Settings.png
LV_IMG_DECLARE(ui_img_record_png);    // assets/Record.png
LV_IMG_DECLARE(ui_img_processor2_png);    // assets/Processor2.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
