// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SEP24_Project

#ifndef _SEP24_PROJECT_UI_H
#define _SEP24_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
